version: '3.7'
services:

  dashboard:
    build: 
      context: ./
    container_name: ${COMPOSE_PROJECT_NAME}_dashboard
    hostname: ${COMPOSE_PROJECT_NAME}_dashboard
    restart: always
    ports:
      - 3838:3838
    networks:
      - network 
    

      
networks:
  network:
    driver: bridge
